### ISSUE TITLE
Does it still works ?

### ISSUE THREAD

**Issue by zobi8225** [jd/google-contacts.el#5]
Hi,
I try to launch google contact, 
It ask me endless time my password and my username.
I think it don't work but i am not sure, i could have make mistake...

(Sorry for my bad english)

**Comment by jd** [comment]
It does work here. So unless you have more information, I'm closing that.

**Comment by jd** [comment]
I actually end up with either no result or an error too. It might be broken.

**Comment by zobi8225** [comment]
thanks.

**Comment by egh** [comment]
@zobi8225 Possibly fixed with #6.

**Comment by zobi8225** [comment]
It still don't work for me...

**Comment by egh** [comment]
well, it was worth a shot! sorry. maybe a problem with your oauth in emacs. Not sure. I'm running on emacs 25 snapshot on ubuntu.

**Comment by kepi** [comment]
@zobi8225 have you red second comment at http://www.emacswiki.org/emacs/GoogleContacts ?

When you first launch google-contacts it will open new tab in your browser and show key which you need to copy and enter in minibuffer in emacs. Than it asks you for password used to encrypt file with your key.

Then every time you try to use google-contacts you have to enter password you used to encrypt the file.

I think you can repeat whole procedure if you simply delete file ~/.emacs.d/oauth2.plstore (make a backup  first)

**Comment by zobi8225** [comment]
Ok, i delete the file ~/.emacs.d/oauth2.plstore and now it s working.
Thx
