### ISSUE TITLE
Encrypt Failed

### ISSUE THREAD

**Issue by MBuchaus** [jd/google-contacts.el#7]
Hi I'm getting an Encrypt Failed message on Oauth attempts ..

helm-M-x: GPG error: "Encrypt failed", "Exit"
GPG is setup and I can decrypt my authinfo.gpg file without interaction..   

Any Ideas.

**Comment by jd** [comment]
google-contacts uses oauth2 which uses auth-source. So clearly not a problem with google-contacts, but one of the others. :(

**Comment by MBuchaus** [comment]
Useing spacemacs.. and there is no other debug info.. to help figure out where the issue is.. 
I get the Oauth session on the browser and copy over the key and emacs looks to be waiting for a bit then I get the GPG error

**Comment by michaelmrose** [comment]
Did anyone fix this?
