### ISSUE TITLE
plstore is irksome; please support authinfo.gpg

### ISSUE THREAD

**Issue by PhilHudson** [jd/google-contacts.el#9]
Emacs already has `auth-sources`, a familiar, tried-and-trusted, built-in API for storing and accessing secrets. I'm sure I'm not alone in finding `plstore` irksome. Please consider supporting other possible values for user option `gcontacts-user-password`: the pathname of a GPG-encrypted netrc/authinfo file storing the token, and/or a user-specified function returning the cleartext token. If nobody with the requisite experience can offer to help, I'm willing to try to implement this, as long as you agree.

**Comment by jd** [comment]
I don't think this library uses `plstore` at all, so…? There's no `gcontacts-user-password` user option.

**Comment by PhilHudson** [comment]
You're right, it's in a dependency, oauth2.el. Sorry for the noise.

**Comment by PhilHudson** [comment]
And I realize now I have two Google Contacts libraries: this one (google-contacts.el) and another called gcontacts.el which defcustoms the `gcontacts-user-password` option.
